### ISSUE TITLE
Clojurescript won't trigger tests

### ISSUE THREAD

**Issue by nenadalm** [jakemcc/lein-test-refresh#44]
Hi. Just starting with clojure/clojurescript.

I have app where some tests are written in clojure using https://github.com/semperos/clj-webdriver and the rest is clojurescript (for now). Is it possible to configure lein-test-refresh so that it reruns test when *.cljs changes? - I didn't find it in docs.

**Comment by jakemcc** [comment]
Welcome to Clojure/ClojureScript!

There currently isn't a way to have tests rerun when a cljs file changes because `lein-test-refresh` doesn't know anything about building ClojureScript so it can't tell when it would be appropriate to run tests (after build is complete).

Depending on how you're building your cljs you might be able to have a command run after a successful build. If so, one option would be to have that command `touch` your Clojure files to trigger a build.

**Comment by nenadalm** [comment]
Thanks. It would be probably also possible to use newer version of clojure tools.namespace and use new funciton scan-dirs https://github.com/clojure/tools.namespace/blob/tools.namespace-0.3.0-alpha2/src/main/clojure/clojure/tools/namespace/dir.clj#L79 with cljs platform as parameter instead of the old deprecated one "scan" https://github.com/jakemcc/lein-test-refresh/blob/78e68a6a8a828daf47116e2d46d54a710844fabe/test-refresh/src/com/jakemccrary/test_refresh.clj#L16

**Comment by nenadalm** [comment]
also when I clone your project, go into "test-refresh" and run "lein test" I receive following error:

```shell
$ lein test
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: select-vars in this context, compiling:(com/jakemccrary/test_refresh_test.clj:24:21)
	at clojure.lang.Compiler.analyze(Compiler.java:6464)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3665)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:957)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6639)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$TryExpr$Parser.parse(Compiler.java:2191)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6632)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$MapExpr.parse(Compiler.java:2981)
	at clojure.lang.Compiler.analyze(Compiler.java:6453)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:537)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler.eval(Compiler.java:6707)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at user$eval85.invoke(form-init65252082954714836.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: select-vars in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6940)
	at clojure.lang.Compiler.resolve(Compiler.java:6884)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6845)
	at clojure.lang.Compiler.analyze(Compiler.java:6427)
	... 99 more
Tests failed.
```

here's my leiningen version:
```shell
$ lein -v
Leiningen 2.5.2 on Java 1.8.0_65 OpenJDK 64-Bit Server VM
```

am I doing something wrong?

**Comment by nenadalm** [comment]
I solved that using simple bash script for now

```shell
#!/usr/bin/env bash

cd "$(dirname "${0}")/.."

while true; do
  if inotifywait -r -e modify src/ | grep -P '(\.clj|\.cljs)'; then
      lein test && notify-send -u low "Tests passed" || notify-send -u critical "Tests failed"
  fi
done
```

**Comment by jakemcc** [comment]
@nenadalm Thanks for noticing the `select-vars` problem. I had removed that function from the non-test source and forgot to remove from the tests.

**Comment by jakemcc** [comment]
> Thanks. It would be probably also possible to use newer version of clojure tools.namespace and use new funciton scan-dirs https://github.com/clojure/tools.namespace/blob/tools.namespace-0.3.0-alpha2/src/main/clojure/clojure/tools/namespace/dir.clj#L79 with cljs platform as parameter instead of the old deprecated one "scan" https://github.com/jakemcc/lein-test-refresh/blob/78e68a6a8a828daf47116e2d46d54a710844fabe/test-refresh/src/com/jakemccrary/test_refresh.clj#L16

You would need to be able to trigger off both clj and cljs changes. Otherwise when you change your clj-webdriver tests you wouldn't have the tests run.

Also, this still doesn't solve the problem of knowing when your ClojureScript source has finished building. I don't know the specifics of your project but I imagine you don't actually want your webdriver tests running until the ClojureScript has been built into JavaScript.

That is probably still a problem with your `inotifywait` solution. It might not be noticeable because of how long it takes for `lein test` to start up though.

One way to change your `inotifywait` script to solve this (potential) problem would be to have it monitor your output directory for changes to the javascript files. When a file changes, then `touch` your test files (something like `touch test/**/**`) to trigger `lein-test-refresh` rerunning your tests with updated javascript.

**Comment by nenadalm** [comment]
lein tests compiles clojurescript before running tests - so no problem here

**Comment by jakemcc** [comment]
Good to know. At this point I am usually using figwheel or not using
leiningen with my cljs builds.

You might see a faster feedback cycle using a cljs auto watcher for
building plus inotifywait and touching a clj file to trigger tests. Might
be worth giving a shot if this way starts to be slow.
