### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by cloojure** [jakemcc/lein-test-refresh#62]
Hi - I'm loving test-refresh and use it all the time.  Unfortunately, I've found a corner case that seems to result in a SOE.  The stacktrace looks like:

```
Ran 97 tests containing 1087 assertions.
0 failures, 0 errors.
Exception in thread "main" java.lang.StackOverflowError, compiling:(/tmp/form-init2179314932373391560.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.StackOverflowError
	at com.jakemccrary.test_refresh$run_tests.invoke(test_refresh.clj)
	at com.jakemccrary.test_refresh$run_tests.invokeStatic(test_refresh.clj:162)
	at com.jakemccrary.test_refresh$run_tests.invoke(test_refresh.clj:156)
	at com.jakemccrary.test_refresh$run_tests.invokeStatic(test_refresh.clj:162)

```

I have a test function that looks like this:
```
  (is (every? t/truthy? (forv [lb (range 0 4)
                               ub (range lb 4) ]
                          (= (t/rng lb ub) (range lb ub)))))
```

In order to force it to fail, I change "ub" to "9" at the end:

```
  (is (every? t/truthy? (forv [lb (range 0 4)
                               ub (range lb 4) ]
                          (= (t/rng lb ub) (range lb 9)))))
```

test-refresh reports the failure as expected.  

```
Testing tst.tupelo.core
FAIL in (t-rng) (core.cljc:547)
expected: (every? t/truthy? (forv [lb (range 0 4) ub (range lb 4)] (= (t/rng lb ub) (range lb 9))))
  actual: (not (every? #object[tupelo.core$truthy_QMARK_ 0x6873b40f "tupelo.core$truthy_QMARK_@6873b40f"] [false false false false false false false false false false]))
```

Then, when I change it back from "9" to "ub", I get an infinite loop that results in the SOE.

Any ideas?

**Comment by cloojure** [comment]
I found a minimal test case.  Main ns

```
(ns clj.core
  (:gen-class))
(defn my-fn [] 1)

```

Testing ns:

```
(ns tst.clj.core
  (:use clj.core
        clojure.test))

(deftest t-my-fn
  (is (#{0 1 2} (my-fn))))
```

Procedure:

1. Start "lein test-refresh".  See it work fine.
2. Delete the "1" from the set in "t-my-fn" & save file. See if fail as it should.
3. Restore the "1" to the set, & save file. See infinite loop -> StackOverflowException

**Comment by jakemcc** [comment]
Interesting. I probably won't be able to look at this over the holidays because of family time.

What version are you on? I recently discovered a stackoverflow error with 0.18.0 that should be fixed in 0.18.1

**Comment by cloojure** [comment]
Hi - Just tested 0.18.1, and the problem is no longer present.   :)
Alan

**Comment by jakemcc** [comment]
Great! Glad to see that was the problem.
